
#server.host = 0.0.0.0


#spring.datasource.url=jdbc:mysql://localhost:3306/Battery?useUnicode=true&serverTimezone=Asia/Seoul


spring:
#  datasource:
#    url: jdbc:mysql://lwc421.iptime.org:3434/Dokkaebi?useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: cilab!23
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#  hibernate:
#    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    ddl-auto: none
#  properties:
#    hibernate:
#      format_sql: true


server:
  port: 8081
  host: localhost
  tcp: 5001
  netty:
    boss-count: 10
    worker-count: 11
    keep-alive: FALSE
    backlog: 100

logging:
  level:
    root: INFO
