server:
  port: 8081
  host: localhost
  tcp: 5000
  netty:
    boss-count: 10
    worker-count: 11
    keep-alive: FALSE
    backlog: 100

spring:
  profiles:
    active: dev

logging:
  level:
    root: INFO


